version: '3.3'
services:
   mysql_drupaldb:
     image: mysql:latest
     container_name: mysql_db
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - net
     environment:
       MYSQL_ROOT_PASSWORD: drupal@root#pass
       MYSQL_DATABASE: drupal
       MYSQL_USER: drupal
       MYSQL_PASSWORD: drupal@123

   drupalweb:
     depends_on:
       - mysql_drupaldb
     container_name: drupal9_web
     image: heydeb/drupal9_composer_drush_ubuntu_nginx_mysql:5
     build: 
       context: docker
     volumes:
      - $PWD/drupal_files:/var/www/html/waterfallhandbook
     ports:
       - "8998:80"
     networks:
       - net
     environment:
       DRUPAL_DB_HOST: mysql_drupaldb:3306
       DRUPAL_DB_USER: drupal
       DRUPAL_DB_PASSWORD: drupal@123
volumes:
    drupal_files:
    db_data:

networks:
   net:
